#ifndef TCPLIBRASPBERRYPI_GLOBAL_H
#define TCPLIBRASPBERRYPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TCPLIBRASPBERRYPI_LIBRARY)
#  define TCPLIBRASPBERRYPI_EXPORT Q_DECL_EXPORT
#else
#  define TCPLIBRASPBERRYPI_EXPORT Q_DECL_IMPORT
#endif

#endif // TCPLIBRASPBERRYPI_GLOBAL_H
